.TH "guake-indicator" "1"
.SH "NAME"
.B guake-indicator
\(em A simple Appindicator that lets you send custom commands to Guake.
.SH "SYNOPSIS"
.PP
\fBguake-indicator
.SH "DESCRIPTION"
.PP
\fBguake-indicator\fR lets you manage your favorite customized commands establishing a new connection with Guake dropdown terminal.
.PP
\fBguake-indicator\fR sticks to your "System Tray" and displays data retrieved from the Guake indicator configuration file (see FILES section for more details)

.SH FILES
\fBguake-indicator\fR builds the menu according to
.I ~/.guake.indicator/guake-indicator.xml
XML file

If this configuration file does not exist a default one will be created.
.PP
Although Guake indicator has a built-in menu editor,
you can customize this file according to your needs with your favorite text editor, just use this schema as a base to add new entries.
The fields are self-explanatory, however, I'm going to give you a more in-depth description of each one:
.TP
.B menu_name
The name that will show up in the indicator itself
.TP
.B tab_name
the name of the guake terminal tab once it is opened (leave black if you don't want automatic autorenaming)
.TP
.B command_after_login
command to send to Guake through his DBUS interface
.TP
.B  dont_show_guake
If set to yes, Guake indicator won't ask Guake to display his main window.
.B  open_in_tab
The index of the Guake tab where guake-indicator will execute the
command.Guake assigns index 0 to the first tab so put in this field the nth
tab-1 number.
If this tag has the attribute named="yes" it contains the name of the Guake tab
.B lfcr
If set to yes a LF (Line Feed) + CR (Carriage return) is sent to Guake after each line
(by default only a line feed (ascii code 10) is sent.
.B guakeindicatorscript
If set to yes enables the Guake indicator scripting function
.PP
The above xml field are all optional (except menu_name) and must be stored
within a XML Host parent field which in turn is enclosed withing a HostGroup
field.You can find more information and a xsd validation file at
http://guake-indicator.ozzyboshi.com.

.SH BUGS
Please report any bug to Alessio Garzi <gun101@email.it>

.SH AUTHOR
\fBguake-indicator\fP was written by Alessio Garzi <gun101@email.it>
.PP
This manual page was written by Alessio Garzi <gun101@email.it>.
